---
- name: Install MinIO on CentOS 7
  hosts: minio
  become: yes
  vars:
    minio_user: minio
    minio_group: minio
    minio_bin_path: /usr/local/bin
    minio_data_dir: /var/minio/data
    minio_config_dir: /etc/minio
    minio_server_addr: ":9000"
    minio_access_key: "minioadmin"
    minio_secret_key: "minioadmin"

  tasks:
    - name: Ensure MinIO group exists
      group:
        name: "{{ minio_group }}"
        state: present

    - name: Ensure MinIO user exists
      user:
        name: "{{ minio_user }}"
        group: "{{ minio_group }}"
        system: yes
        createhome: no

    - name: Download MinIO binary
      get_url:
        url: https://dl.min.io/server/minio/release/linux-amd64/minio
        dest: "{{ minio_bin_path }}/minio"
        mode: '0755'

    - name: Ensure MinIO data directory exists
      file:
        path: "{{ minio_data_dir }}"
        state: directory
        owner: "{{ minio_user }}"
        group: "{{ minio_group }}"

    - name: Ensure MinIO config directory exists
      file:
        path: "{{ minio_config_dir }}"
        state: directory
        owner: "{{ minio_user }}"
        group: "{{ minio_group }}"

    - name: Create MinIO systemd service file
      template:
        src: minio.service.j2
        dest: /etc/systemd/system/minio.service
      notify: restart minio

    - name: Enable and start MinIO service
      systemd:
        name: minio
        enabled: yes
        state: started

  handlers:
    - name: restart minio
      systemd:
        name: minio
        state: restarted
        daemon_reload: yes

